Mini Batch Gradient Descent from scratch

In [31]:
import numpy as np
import random

from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [32]:
X,y = load_diabetes(return_X_y=True)
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=2,test_size=0.2)

In [33]:
reg = LinearRegression()
reg.fit(X_train,y_train)

y_pred = reg.predict(X_test)

In [34]:
print(reg.intercept_)
print(reg.coef_)

151.88334520854633
[  -9.16088483 -205.46225988  516.68462383  340.62734108 -895.54360867
  561.21453306  153.88478595  126.73431596  861.12139955   52.41982836]


In [35]:
r2 = r2_score(y_test,y_pred)
r2

0.4399387660024645

In [68]:
class MiniBatchGDRegressor():
    def __init__(self,epochs = 75,learning_rate = 0.01,batch_size = 10):
        self.intercept_ = None
        self.coef_ = None
        self.epochs = epochs
        self.lr = learning_rate
        self.batch_size = batch_size
        
    def fit(self,X_train,y_train):
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
            for j in range(int(X_train.shape[0] / self.batch_size)):
                #generating multiple random numbers(rows in this case)
                batch = random.sample(range(X_train.shape[0]),self.batch_size)
                
                y_pred =np.dot(X_train[batch],self.coef_) + self.intercept_
                der_intercept = -2 * np.mean(y_train[batch] - y_pred)
                self.intercept_ = self.intercept_ - self.lr * der_intercept
                
                der_coef = -2 * np.dot((y_train[batch] - y_pred),X_train[batch])
                self.coef_ = self.coef_ - self.lr * der_coef
                
        #print(self.intercept_,self.coef_)
                
        
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [75]:
mbgd = MiniBatchGDRegressor(epochs = 75,learning_rate=0.01,batch_size = int(X_train.shape[0]/10))
mbgd.fit(X_train,y_train)

In [76]:
mbgd.coef_

array([ 3.94786285e+01, -1.12573292e+02,  4.16931234e+02,  2.84249736e+02,
        1.85338993e-01, -6.11149450e+01, -1.80827174e+02,  1.21766300e+02,
        3.75521262e+02,  1.23281046e+02])

In [77]:
mbgd.intercept_

150.16066597793204

In [78]:
y_pred = mbgd.predict(X_test)

In [79]:
r2s = r2_score(y_test,y_pred)
r2s

0.44752229302661006

In [80]:
"""
What random.sample() method does.
"""

random.sample(range(X_train.shape[0]),10)

[81, 6, 227, 341, 217, 290, 275, 160, 154, 218]

Mini batch gradient descent using sklearn.

The fact is that there is no built in class for mini-batch gradient descent. You have to come up with your own solution to perfomr mini batch gd.

In [81]:
from sklearn.linear_model import SGDRegressor

In [82]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.2)

partial_fit(X, y, sample_weight=None)


Perform one epoch of stochastic gradient descent on given samples.

In [89]:
batch_size = 35

#epoch is 100
for i in range(100):
    batch = random.sample(range(X_train.shape[0]),batch_size)
    sgd.partial_fit(X_train[batch],y_train[batch])
    

In [90]:
sgd.coef_

array([  -0.7113234 , -211.43262086,  499.84967973,  332.50693335,
        -49.41104497, -127.44867408, -190.26912592,  120.38638676,
        477.53591312,   88.49343577])

In [91]:
sgd.intercept_

array([156.11586344])

In [92]:
y_pred = sgd.predict(X_test)

In [93]:
r2s = r2_score(y_test,y_pred)
r2s

0.45274526049604