Think about this notebook as a webpage, where the user will give us the detail of new passengers. But to be honest, this is a hectic work. So, we use <b style = 'color:red'>sklearn's pipeline</b> instead which is shown in another notebook. Here, we just do things <b style = 'color:orange'>manually</b>. Just imagine, while doing all these works, if something goes wrong what will affect on production stage. That's why it's wiser to use sklearn's pipelines

In [21]:
import pickle
import numpy as np

In [22]:
"""
In load(), we decode these files from pkl format to objects.
"""
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [32]:
#Pclass	SibSp	Parch	Fare/age/sex/embarked
test_input = np.array([2,0,0,13.23,42,'female','S'],dtype = object).reshape(1,7)
#np.array([[2,0,0,13.23,42,'female','S']],dtype = object)

In [33]:
test_input

array([[2, 0, 0, 13.23, 42, 'female', 'S']], dtype=object)

In [36]:
print(test_input[:,5].reshape(1,1))

[['female']]


In [40]:
test_input_sex = ohe_sex.transform(test_input[:,5].reshape(1,1))

In [43]:
test_input_sex

array([[1., 0.]])

In [42]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [44]:
test_input_embarked

array([[0., 0., 1.]])

In [52]:
test_input_transformed = np.concatenate((test_input[:,0:5],test_input_sex,test_input_embarked),axis = 1)

In [53]:
test_input_transformed.shape

(1, 10)

In [54]:
clf.predict(test_input_transformed)

array([1], dtype=int64)