### What is a tensor?

Tensor is nothing but a container which stores data for Machine Learning models to learn from them. It mostly works with numerical values but in rare ocassions one might have to deal with strings and characters etc. It's a data structure that generally is a <b style = "color:purple">n-d</b> array.

In [1]:
import numpy as np

#### Scalar / 0-D tensor

Scalar is just a variable/object with a single value.

In [11]:
scalar_ = np.array(5)
scalar_                     #This scalar_ is an example of scalar or 0-D tensor. 

array(5)

In [40]:
scalar_.shape

()

In [25]:
scalar_.ndim                #Gives us the dimension of the scalar or 0-D tensor.

0

#### Vector / 1-D tensor
1-D tensor is simply a 1-D array. i.e. Vector. It contains a list of values(scalars). <br><br>
In other words, 1-D tensor is a collection of 0-D tensors.

In [15]:
vector_ = np.array([1,2,3,4,5])
vector_

array([1, 2, 3, 4, 5])

In [41]:
vector_.shape

(5,)

In [16]:
vector_.ndim

1

In [19]:
vector_.size            #no. of dimensions of vector or the number of elements in the vector.

5

#### Matrix / 2-D tensor.

2-D tensor is a collection of 1-D tensors. That is, when one adds up vectors to form a 2-D array then it is known as a 2-D tensor or Matrix.

In [22]:
matrix_ = np.arange(1,13).reshape(4,3)

In [23]:
matrix_

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
matrix_.ndim      #Gives us the dimension of the Matrix or 2-D tensor.

2

In [28]:
matrix_.size      #gives us the no. of elements in the matrix.

12

#### 3-D tensor

A collection of 2-D tensors/ Matrices forms a 3-D tensor. An image is an example of 3-D tensor because it forms by making 3 separate images in RGB and then by adding up these 3 matrices.

In [31]:
tensor_3D = np.arange(24).reshape(2,3,4)
tensor_3D

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [32]:
tensor_3D.shape

(2, 3, 4)

In [33]:
tensor_3D.size

24

In [34]:
tensor_3D.ndim

3

#### 4-D tensor and 5-D tensor

A collection of 3-D tensors. Or in a way you can say that a vector of 3-D tensors. 

Matrix of 3-D tensors or a vector of 4-D tensors.

In [36]:
tensor_4d = np.arange(36).reshape(2,2,3,3)
tensor_4d

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]],

        [[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]]])

In [39]:
tensor_4d.ndim

4

In [38]:
tensor_4d.size

36

In [37]:
tensor_4d.shape

(2, 2, 3, 3)

#### N-D tensor
N-D tensor is a collection of (N-1)-D tensors in general.